export const NAV_LINKS = [
  { label: 'Explore', url: '/explore?tracking_source=nav20' },
  { label: 'Resources', url: '/resources/commissions?tracking_source=nav20' },
]

export const HIRE_BENEFITS = [
  {
    title: "Access to the world's best creators",
    text: 'Get matched from a pool of over 2 million qualified freelancers',
  },
  {
    title: 'All the right tools in one place',
    text: 'Start conversations, share files, and join video calls with candidates',
  },
  {
    title: 'Secure payments',
    text: 'Pay seamlessly and securely with a debit or credit card on Behance',
  },
  {
    title: 'No platform fee with Behance Pro',
    text: 'Platform fees are waived for freelancers with Behance Pro',
  },
]

export const HIRE_STEPS = [
  {
    title: 'Review recommendations',
    text: 'Share your requirements with recommended freelancers, and review their proposals.',
  },
  {
    title: 'Hire & collaborate',
    text: 'Start conversations, share files, and join video calls to discuss your job details.',
  },
  {
    title: 'Pay securely on platform',
    text: 'Pay seamlessly with a debit or credit card on Behance.',
  },
]

export const JOB_LISTINGS = [
  {
    title: 'Full UI/UX Redesign and Development for Website',
    company: 'YCCYF',
    type: 'Freelance',
    location: 'Remote',
    url: 'https://www.behance.net/joblist/freelance/532999/Full-UIUX-Redesign-and-Development-for-Website',
  },
  {
    title: 'Graphic Designer',
    company: 'Design Dimensions',
    type: 'Full-time',
    location: 'New Delhi, India',
    url: 'https://www.behance.net/joblist/fulltime/363357/Graphic-Designer',
  },
  {
    title: 'Motion Designer',
    company: 'Design Dimensions',
    type: 'Full-time',
    location: 'New Delhi, India',
    url: 'https://www.behance.net/joblist/fulltime/363361/Motion-Designer',
  },
  {
    title: 'Product/UI Design Refinement for LOOM Indie Social App Beta',
    company: 'LOOM (independent social app)',
    type: 'Freelance',
    location: 'Remote',
    url: 'https://www.behance.net/joblist/freelance/533521/ProductUI-Design-Refinement-for-LOOM-Indie-Social-App-Beta',
  },
  {
    title: 'Social Media Designer',
    company: 'Design Dimensions',
    type: 'Full-time',
    location: 'New Delhi, India',
    url: 'https://www.behance.net/joblist/fulltime/363355/Social-Media-Designer',
  },
  {
    title: 'Branding Refresh With Enhanced Call Out Badges and Hero Ingredient Features',
    company: 'Small Batch Soaps',
    type: 'Freelance',
    location: 'Remote',
    url: 'https://www.behance.net/joblist/freelance/531485/Branding-Refresh-With-Enhanced-Call-Out-Badges-and-Hero-Ingredient-Features',
  },
  {
    title: 'Visual Communication Designer',
    company: 'Design Dimensions',
    type: 'Full-time',
    location: 'New Delhi, India',
    url: 'https://www.behance.net/joblist/fulltime/362369/Visual-Communication-Designer',
  },
  {
    title: 'Video Lead',
    company: 'Engage Digital Partners',
    type: 'Full-time',
    location: 'Bangalore · Delhi · Mumbai',
    url: 'https://www.behance.net/joblist/fulltime/362385/Video-Lead',
  },
  {
    title: 'Mid/Senior level Designer',
    company: 'IDFX Design',
    type: 'Full-time',
    location: 'Mumbai, India',
    url: 'https://www.behance.net/joblist/fulltime/362153/MidSenior-level-Designer',
  },
  {
    title: 'Event Designer Needed in Ho Chi Minh City for Modern, Youthful Style',
    company: 'Coffee Brand',
    type: 'Freelance',
    location: 'Remote',
    url: 'https://www.behance.net/joblist/freelance/528983/Event-Designer-Needed-in-Ho-Chi-Minh-City-for-Modern-Youthful-Style',
  },
]

export const STATS = [
  { label: 'Project Views', value: '1,763', url: '/saifynaz/analytics' },
  { label: 'Appreciations', value: '331', url: '/saifynaz/analytics' },
  { label: 'Followers', value: '21', url: '/saifynaz/followers' },
  { label: 'Following', value: '9', url: '/saifynaz/following' },
]

export const TABS = [
  { label: 'Info', url: '/saifynaz/info' },
  { label: 'Work', url: '/saifynaz/projects', active: true },
  { label: 'Services', url: '/saifynaz/services' },
  { label: 'Moodboards', url: '/saifynaz/moodboards' },
  { label: 'Appreciations', url: '/saifynaz/appreciated' },
]

export const PROJECTS = [
  {
    title: 'Wedding Travel & Hospitality — Website UI/UX Design',
    url: 'https://www.behance.net/gallery/255384245/Wedding-Travel-Hospitality-Website-UIUX-Design',
    img: 'https://mir-s3-cdn-cf.behance.net/projects/404/c24aae255384245.Y3JvcCwxMzE4LDEwMzEsNTIsMA.png',
    appreciations: 5,
    views: 11,
    category: 'UX/UI',
  },
  {
    title: 'What I Cook — Graphic Design',
    url: 'https://www.behance.net/gallery/255243149/What-I-Cook-Graphic-Design',
    img: 'https://mir-s3-cdn-cf.behance.net/projects/404/88cef4255243149.Y3JvcCwxMzE4LDEwMzEsMjksMA.png',
    appreciations: 6,
    views: 12,
    category: 'Graphic Design',
  },
  {
    title: 'White-Label Hotel & Flight Voucher Design',
    url: 'https://www.behance.net/gallery/254116933/White-Label-Hotel-Flight-Voucher-Design',
    img: 'https://mir-s3-cdn-cf.behance.net/projects/404/f25276254116933.Y3JvcCw3NTUwLDU5MDYsNTYwLDA.png',
    appreciations: 6,
    views: 32,
    category: 'Graphic Design',
  },
  {
    title: '87 People. 87 Personalities. 87 Sketches.',
    url: 'https://www.behance.net/gallery/254055901/87-People-87-Personalities-87-Sketches',
    img: 'https://mir-s3-cdn-cf.behance.net/projects/404/f66121254055901.Y3JvcCw3NTUwLDU5MDYsMjE2OCww.png',
    appreciations: 4,
    views: 26,
    category: 'Illustration',
  },
  {
    title: 'UX Case Study: KalakaarHub – A Handmade Art & Craft App',
    url: 'https://www.behance.net/gallery/230294621/UX-Case-Study-KalakaarHub-A-Handmade-Art-Craft-App',
    img: 'https://mir-s3-cdn-cf.behance.net/projects/404/285524230294621.Y3JvcCwxNjkyLDEzMjQsOCww.png',
    appreciations: 10,
    views: 118,
    category: 'UX/UI',
  },
  {
    title: 'Voice To Note Redesign Case Study',
    url: 'https://www.behance.net/gallery/235068659/Voice-To-Note-Redesign-Case-Study',
    img: 'https://mir-s3-cdn-cf.behance.net/projects/404/a261ff235068659.Y3JvcCwzMzg1LDI2NDgsMTYsMA.png',
    appreciations: 10,
    views: 59,
    category: 'UX/UI',
  },
  {
    title: 'Interactive Food Delivery App Redesign',
    url: 'https://www.behance.net/gallery/216876051/Interactive-Food-Delivery-App-Redesign',
    img: 'https://mir-s3-cdn-cf.behance.net/projects/404/f916f2216876051.Y3JvcCwxMjEyLDk0OCwwLDA.png',
    appreciations: 11,
    views: 88,
    category: 'UX/UI',
  },
  {
    title: 'VR OTT platform inspired by YouTube',
    url: 'https://www.behance.net/gallery/207952307/VR-OTT-platform-inspired-by-YouTube',
    img: 'https://mir-s3-cdn-cf.behance.net/projects/404/b61dbf207952307.Y3JvcCw1NDEwLDQyMzIsMzkyMyww.png',
    appreciations: 8,
    views: 110,
    category: 'UX/UI',
  },
  {
    title: 'Show Time: Movie Seat Booking App UI Design',
    url: 'https://www.behance.net/gallery/206078421/Show-Time-Movie-Seat-Booking-App-UI-Design',
    img: 'https://mir-s3-cdn-cf.behance.net/projects/404/c15e27206078421.Y3JvcCw1NTc0LDQzNjAsMjIwNyww.png',
    appreciations: 15,
    views: 119,
    category: 'UX/UI',
  },
  {
    title: 'Animal coloring book A-Z',
    url: 'https://www.behance.net/gallery/232007255/Animal-coloring-book-A-Z',
    img: 'https://mir-s3-cdn-cf.behance.net/projects/404/458d9c232007255.Y3JvcCwzMDExLDIzNTUsOTU0LDMxMw.png',
    appreciations: 7,
    views: 38,
    category: 'Illustration',
  },
  {
    title: 'Graphics design post',
    url: 'https://www.behance.net/gallery/233574285/Graphics-design-post',
    img: 'https://mir-s3-cdn-cf.behance.net/projects/404/6d53b6233574285.Y3JvcCwzMzc1LDI2MzksMCw0Njc.png',
    appreciations: 7,
    views: 20,
    category: 'Graphic Design',
  },
  {
    title: 'Visual storytelling through poster design',
    url: 'https://www.behance.net/gallery/233782253/Visual-storytelling-through-poster-design',
    img: 'https://mir-s3-cdn-cf.behance.net/projects/404/aea5e8233782253.Y3JvcCwzMzc1LDI2MzksMCwxNjc.png',
    appreciations: 7,
    views: 16,
    category: 'Graphic Design',
  },
]

export const JOBLIST_TABS = [
  { label: 'All Jobs', url: '/joblist', active: true },
  { label: 'Freelance', url: '/joblist?jobType=freelance' },
  { label: 'Full-Time', url: '/joblist?jobType=fulltime&jobType=contract' },
]

export const JOBLIST_DETAILS = [
  {
    title: 'Full UI/UX Redesign and Development for Website',
    company: 'YCCYF',
    type: 'Freelance',
    workMode: 'Remote',
    location: 'Remote',
    salary: 'US$1,000-2,500',
    url: 'https://www.behance.net/joblist/freelance/532999/Full-UIUX-Redesign-and-Development-for-Website',
  },
  {
    title: 'Web Designer / Art Director — TEAMIO Public Website in Figma',
    company: 'TEAMIO',
    type: 'Freelance',
    workMode: 'Remote',
    location: 'Remote',
    salary: 'US$1,000-2,500',
    logo: 'https://mir-s3-cdn-cf.behance.net/9579cd9a744aa8ec68693509532cb41a/2291cf9e-c2ce-4eaf-b486-41838b970b8a_acc_180x180.png',
    url: 'https://www.behance.net/joblist/freelance/533541/Web-Designer-Art-Director-TEAMIO-Public-Website-in-Figma',
  },
  {
    title: 'Motion Designer',
    company: 'Design Dimensions',
    type: 'Full-Time',
    workMode: 'On-site',
    location: 'New Delhi, India',
    salary: 'US$300,000-600,000 Per Year',
    pro: true,
    logo: 'https://mir-s3-cdn-cf.behance.net/f727b54e226294891d9ea1884742b895/a96606f8-72af-42f7-8f2d-4846015aaedb_acc_180x180.png',
    url: 'https://www.behance.net/joblist/fulltime/363361/Motion-Designer',
  },
  {
    title: 'Graphic Designer',
    company: 'Design Dimensions',
    type: 'Full-Time',
    workMode: 'On-site',
    location: 'New Delhi, India',
    salary: 'INR - ₹500,000-800,000 Per Year',
    pro: true,
    logo: 'https://mir-s3-cdn-cf.behance.net/d06aa5e3657b44e48115ef1c4787fd3b/c7c09ed9-35dd-4410-b2e6-6c6746b9ac9d_acc_180x180.png',
    url: 'https://www.behance.net/joblist/fulltime/363357/Graphic-Designer',
  },
  {
    title: 'Social Media Designer',
    company: 'Design Dimensions',
    type: 'Full-Time',
    workMode: 'On-site',
    location: 'New Delhi, India',
    salary: 'INR - ₹500,000-800,000 Per Year',
    pro: true,
    logo: 'https://mir-s3-cdn-cf.behance.net/9a1defaccaa5750ab4b74340ef8d8b3c/cb006a5c-3ab4-416f-b457-68745841f2c9_acc_180x180.png',
    url: 'https://www.behance.net/joblist/fulltime/363355/Social-Media-Designer',
  },
  {
    title: 'Branding Refresh With Enhanced Call Out Badges and Hero Ingredient Features',
    company: 'Small Batch Soaps',
    type: 'Freelance',
    workMode: 'Remote',
    location: 'Remote',
    salary: 'US$1,000-2,500',
    logo: 'https://mir-s3-cdn-cf.behance.net/6bf79b062d539cddffabf18c12c03a3d/bfa946e5-9576-4e08-8ce4-835ee0340261_acc_180x180.jpg',
    url: 'https://www.behance.net/joblist/freelance/531485/Branding-Refresh-With-Enhanced-Call-Out-Badges-and-Hero-Ingredient-Features',
  },
  {
    title: 'Photographer / Videographer',
    company: 'Design Dimensions',
    type: 'Full-Time',
    workMode: 'On-site',
    location: 'New Delhi, India',
    salary: 'INR - ₹500,000-800,000 Per Year',
    pro: true,
    logo: 'https://mir-s3-cdn-cf.behance.net/028bcd50661cf99a5ee40d2a81e68e83/26218cee-d85e-4324-9d43-ae76fcfd3dfa_acc_180x180.png',
    url: 'https://www.behance.net/joblist/fulltime/363351/Photographer-Videographer',
  },
  {
    title: 'Event Designer Needed in Ho Chi Minh City for Modern, Youthful Style',
    company: 'Coffee Brand',
    type: 'Freelance',
    workMode: 'Remote',
    location: 'Remote',
    salary: 'US$1,000-2,500',
    url: 'https://www.behance.net/joblist/freelance/528983/Event-Designer-Needed-in-Ho-Chi-Minh-City-for-Modern-Youthful-Style',
  },
  {
    title: 'Translation Services Needed for Multiple Languages',
    company: 'Studio 5creative',
    type: 'Freelance',
    workMode: 'Remote',
    location: 'Remote',
    salary: 'US$2,500-5,000',
    url: 'https://www.behance.net/joblist/freelance/533259/Translation-Services-Needed-for-Multiple-Languages',
  },
  {
    title: 'Architectural Portfolio and Website Graphic Enhancement Collaboration',
    company: 'Remote',
    type: 'Freelance',
    workMode: 'Remote',
    location: 'Remote',
    salary: 'US$2,500-5,000',
    logo: 'https://pps.services.adobe.com/api/profile/8F3A3E6059B07CFD0A495D2C@AdobeID/image/36685fca-ceb1-4f9d-be71-d4673e4a81e7/276',
    url: 'https://www.behance.net/joblist/freelance/532839/Architectural-Portfolio-and-Website-Graphic-Enhancement-Collaboration',
  },
  {
    title: 'Writer, Design, and Engineering Services Needed',
    company: 'Remote',
    type: 'Freelance',
    workMode: 'Remote',
    location: 'Remote',
    salary: 'US$1,000-2,500',
    logo: 'https://pps.services.adobe.com/api/profile/5497048F64E086CB0A495CC1@AdobeID/image/b94115fb-08a7-43a9-9ac8-12e58efc4bde/276',
    url: 'https://www.behance.net/joblist/freelance/533359/Writer-Design-and-Engineering-Services-Needed',
  },
  {
    title: 'Video Lead',
    company: 'Engage Digital Partners',
    type: 'Full-Time',
    workMode: 'Hybrid',
    location: 'Bangalore, India + 2 others',
    salary: 'INR - ₹2,500,000-3,000,000 Per Year',
    pro: true,
    logo: 'https://mir-s3-cdn-cf.behance.net/5e9ff044685548b4198dc04ceb3a25c6/7b6c18df-126b-424b-be55-53c7fa9e2bb1_acc_180x180.png',
    url: 'https://www.behance.net/joblist/fulltime/362385/Video-Lead',
  },
  {
    title: 'Interior Design for 3 BHK Home',
    company: 'Remote',
    type: 'Freelance',
    workMode: 'Remote',
    location: 'Remote',
    salary: 'US$1,000-2,500',
    url: 'https://www.behance.net/joblist/freelance/533129/Interior-Design-for-3-BHK-Home',
  },
  {
    title: '2D Animators Needed for Brand Essence-Style Video',
    company: 'e26 Creative',
    type: 'Freelance',
    workMode: 'Remote',
    location: 'Remote',
    salary: 'US$2,500-5,000',
    logo: 'https://mir-s3-cdn-cf.behance.net/0bf8c68d236084f14404b8bd4bebccf3/c3ba11c0-44c2-49da-989a-3cc3d7a71a3c_acc_180x180.png',
    url: 'https://www.behance.net/joblist/freelance/533403/2D-Animators-Needed-for-Brand-Essence-Style-Video',
  },
  {
    title: 'Video Editing Services for Individual Videos',
    company: 'Remote',
    type: 'Freelance',
    workMode: 'Remote',
    location: 'Remote',
    salary: 'US$1,000-2,500',
    url: 'https://www.behance.net/joblist/freelance/531423/Video-Editing-Services-for-Individual-Videos',
  },
  {
    title: 'Video Editor',
    company: 'Design Dimensions',
    type: 'Full-Time',
    workMode: 'On-site',
    location: 'New Delhi, India',
    salary: 'INR - ₹500,000-800,000 Per Year',
    pro: true,
    logo: 'https://mir-s3-cdn-cf.behance.net/0bcb10dc11f5446a2509a54ca60f2a28/7ff0ff26-f8c1-4e48-875e-4404d9cfd220_acc_180x180.png',
    url: 'https://www.behance.net/joblist/fulltime/362371/Video-Editor',
  },
  {
    title: 'Visual Communication Designer',
    company: 'Design Dimensions',
    type: 'Full-Time',
    workMode: 'On-site',
    location: 'New Delhi, India',
    salary: 'INR - ₹500,000-800,000 Per Year',
    pro: true,
    logo: 'https://mir-s3-cdn-cf.behance.net/fe39e05cc0796cadd96ec92a274e78bb/5e34d3a5-b771-4341-802e-a145d80f0a54_acc_180x180.png',
    url: 'https://www.behance.net/joblist/fulltime/362369/Visual-Communication-Designer',
  },
  {
    title: 'Video Editor',
    company: 'Inclusive Minds',
    type: 'Full-Time',
    workMode: 'On-site',
    location: 'Hyderabad, India',
    salary: 'INR - ₹800,000-1,500,000 Per Year',
    pro: true,
    logo: 'https://mir-s3-cdn-cf.behance.net/9a60e46c3c49d6dd9abc9af3c056eef9/c1e2ecfe-6e13-49ff-99fa-8fa50ec6104b_acc_180x180.png',
    url: 'https://www.behance.net/joblist/fulltime/362185/Video-Editor',
  },
  {
    title: 'Mid/Senior level Designer',
    company: 'IDFX Design',
    type: 'Full-Time',
    workMode: 'On-site',
    location: 'Mumbai, India',
    salary: null,
    pro: true,
    logo: 'https://mir-s3-cdn-cf.behance.net/ccfdcd08e379beb30eee35a124ff7c88/10ee75aa-2166-4ee6-b4f4-d0048a70f4ca_acc_180x180.png',
    url: 'https://www.behance.net/joblist/fulltime/362153/MidSenior-level-Designer',
  },
  {
    title: '2D Animated Brand Essence Video Illustrators Needed',
    company: 'e26 Creative',
    type: 'Freelance',
    workMode: 'Remote',
    location: 'Remote',
    salary: 'US$1,000-2,500',
    logo: 'https://mir-s3-cdn-cf.behance.net/0bf8c68d236084f14404b8bd4bebccf3/c3ba11c0-44c2-49da-989a-3cc3d7a71a3c_acc_180x180.png',
    url: 'https://www.behance.net/joblist/freelance/533401/2D-Animated-Brand-Essence-Video-Illustrators-Needed',
  },
]

export const HIRE_CATEGORIES = [
  { label: 'Graphic Design', img: 'https://a5.behance.net/b6de958fa60333a6b07e7b72087bb95f4bff2f22/img/hire/avatars-graphic-design.1x.webp', url: '/hire/browse?search=Graphic+Design&tracking_source=hire_landing' },
  { label: 'Logo Design', img: 'https://a5.behance.net/b6de958fa60333a6b07e7b72087bb95f4bff2f22/img/hire/avatars-logo-design.1x.webp', url: '/hire/browse?category=logo-design&tracking_source=hire_landing' },
  { label: 'Branding Services', img: 'https://a5.behance.net/b6de958fa60333a6b07e7b72087bb95f4bff2f22/img/hire/avatars-branding-services.1x.webp', url: '/hire/browse?category=branding-services&tracking_source=hire_landing' },
  { label: 'Website Design', img: 'https://a5.behance.net/b6de958fa60333a6b07e7b72087bb95f4bff2f22/img/hire/avatars-website-design.1x.webp', url: '/hire/browse?category=website-design&tracking_source=hire_landing' },
  { label: 'Social Media Design', img: 'https://a5.behance.net/b6de958fa60333a6b07e7b72087bb95f4bff2f22/img/hire/avatars-social-media-design.1x.webp', url: '/hire/browse?category=social-media-design&tracking_source=hire_landing' },
  { label: 'Illustrations', img: 'https://a5.behance.net/b6de958fa60333a6b07e7b72087bb95f4bff2f22/img/hire/avatars-illustrations.1x.webp', url: '/hire/browse?category=illustrations&tracking_source=hire_landing' },
  { label: 'Architecture & Interior Design', img: 'https://a5.behance.net/b6de958fa60333a6b07e7b72087bb95f4bff2f22/img/hire/avatars-architecture-interior-design.1x.webp', url: '/hire/browse?category=architecture-interior-design&tracking_source=hire_landing' },
  { label: 'UI/UX Design', img: 'https://a5.behance.net/b6de958fa60333a6b07e7b72087bb95f4bff2f22/img/hire/avatars-ui-ux-design.1x.webp', url: '/hire/browse?category=ui-ux-design&tracking_source=hire_landing' },
]

export const HIRE_TALENT_TABS = ['All', 'Logo Designers', 'Brand Designers', 'Illustrators', 'UI/UX Designers']

export const TESTIMONIALS = [
  {
    quote: 'Absolutely great Designer to work with. Prompt response, professional approach and beautiful designs. A DELIGHT TO WORK WITH!',
    name: 'Nadia Fernandez',
    img: 'https://a5.behance.net/b6de958fa60333a6b07e7b72087bb95f4bff2f22/img/hire/freelance-hirers/nadia-fernandez.webp',
    url: 'https://www.behance.net/nadiafernandez7',
  },
  {
    quote: "Amazing work as usual! This is my second time working with Enrico and it won't be the last. He created some awesome design assets for a project that helped me elevate the overall brand identity in a professional and timely manner.",
    name: 'Ulysses Design Co',
    img: 'https://a5.behance.net/b6de958fa60333a6b07e7b72087bb95f4bff2f22/img/hire/freelance-hirers/ulysses-design-co.webp',
    url: 'https://www.behance.net/ulyssesdesignco',
  },
  {
    quote: 'I had a fantastic experience working with Lindsey. Her professionalism, expertise, and communication skills made the project smooth and successful. Highly recommended!',
    name: 'Kira Koroknai',
    img: 'https://a5.behance.net/b6de958fa60333a6b07e7b72087bb95f4bff2f22/img/hire/freelance-hirers/kira-koroknai.webp',
    url: 'https://www.behance.net/koroknaikira',
  },
  {
    quote: 'Very creative, smart, friendly and professional. He listens to your needs and comes up with amazing ideas. Great communication. I am honestly shocked for the price that I got my brand identity for. HIGHLY RECOMMEND!!!!',
    name: 'Oktay Taimour',
    img: 'https://a5.behance.net/b6de958fa60333a6b07e7b72087bb95f4bff2f22/img/hire/freelance-hirers/oktay-taimour.webp',
    url: 'https://www.behance.net/oktaytaimour',
  },
  {
    quote: 'Working with Olga was such a pleasure! She executed the brief beyond expectations. 10//10 recommend!',
    name: 'Max Hofert',
    img: 'https://a5.behance.net/b6de958fa60333a6b07e7b72087bb95f4bff2f22/img/hire/freelance-hirers/max-hofert.webp',
    url: 'https://www.behance.net/maxhofert',
  },
  {
    quote: 'It has been an absolute pleasure working with Joey! He is very responsive and easy to collaborate with. He is also a very talented illustrator, able to bring my vision to life almost instantly. It is clear that he puts a lot of heart in his work and anyone should be lucky to work with him.',
    name: 'Egzona Morina',
    img: 'https://a5.behance.net/b6de958fa60333a6b07e7b72087bb95f4bff2f22/img/hire/freelance-hirers/egzona-morina.webp',
    url: 'https://www.behance.net/xheladifoundat',
  },
  {
    quote: 'I absolutely loved working with Silver Stag. It was easy communicating my vision and it was definitely brought to life. 100% would recommend.',
    name: 'Rosmil Garcia',
    img: 'https://a5.behance.net/b6de958fa60333a6b07e7b72087bb95f4bff2f22/img/hire/freelance-hirers/rosmil-garcia.webp',
    url: 'https://www.behance.net/rosmilgarcia1',
  },
  {
    quote: 'Absolutely creative and amazing! She was very patient with us through all the edits the clients kept requesting. Thank you Carolina for the amazing work!',
    name: 'Sarah Scharaf',
    img: 'https://a5.behance.net/b6de958fa60333a6b07e7b72087bb95f4bff2f22/img/hire/freelance-hirers/sarah-scharaf.webp',
    url: 'https://www.behance.net/sarahscharaf',
  },
  {
    quote: "Wow, I'm genuinely impressed! The website design feels fresh and modern. The brand style guide and logos? Spot on and really professional. If you're after a memorable brand presence, Martynas is a top pick!",
    name: 'Lukas Baranovas',
    img: 'https://a5.behance.net/b6de958fa60333a6b07e7b72087bb95f4bff2f22/img/hire/freelance-hirers/lukas-baranovas.webp',
    url: 'https://www.behance.net/lukassmerauskas',
  },
  {
    quote: "Kaylee is amazing! The quality of her work is outstanding, she provides timely updates, is thoughtful, wildly creative and goes the extra mile to make sure you love the end product!",
    name: 'Caitlin-Jessica Foster',
    img: 'https://a5.behance.net/b6de958fa60333a6b07e7b72087bb95f4bff2f22/img/hire/freelance-hirers/caitlin-jessica-foster.webp',
    url: 'https://www.behance.net/caitlinjessica',
  },
  {
    quote: 'Alyona is an amazing professional: polite, constructive, full of ideas, works fast and makes astonishing illustrations! I enjoyed working with her and will happily recommend her to everyone!',
    name: 'Ilya Chidyakin',
    img: 'https://a5.behance.net/b6de958fa60333a6b07e7b72087bb95f4bff2f22/img/hire/freelance-hirers/Ilya-chidyakin.webp',
    url: 'https://www.behance.net/ilyachidyakin',
  },
  {
    quote: 'She is a genius, super attentive and detail-oriented. Solution-oriented and dynamic in her work, highly recommended!',
    name: 'Francisco Rivero',
    img: 'https://a5.behance.net/b6de958fa60333a6b07e7b72087bb95f4bff2f22/img/hire/freelance-hirers/francisco-rivero.webp',
    url: 'https://www.behance.net/franciscorivero3',
  },
  {
    quote: "Very happy with the work that Robin did. He pays attention to the smallest details and is very communicative along the web design process. We couldn't ask for a better person for the job and we will most definitely continue to work with him on future projects.",
    name: 'Mariah Fabe',
    img: 'https://a5.behance.net/b6de958fa60333a6b07e7b72087bb95f4bff2f22/img/hire/freelance-hirers/mariah-fabe.webp',
    url: 'https://www.behance.net/mariahfabe',
  },
  {
    quote: 'Daniel was very easy to work with and he was able to create exactly what I asked for! Thank you so much, Daniel!',
    name: 'Karina H',
    img: 'https://a5.behance.net/b6de958fa60333a6b07e7b72087bb95f4bff2f22/img/hire/freelance-hirers/karina-h.webp',
    url: 'https://www.behance.net/karinahuizar',
  },
]

export const HIRE_STATS = [
  { value: '50M+', label: 'Over 50 million members in the Behance community' },
  { value: 'Billions', label: 'Creative work gets seen billions of times every year on Behance' },
  { value: '2006', label: 'Founded in 2006, Behance has been a trusted network for over 15 years' },
]

export const HIRE_FOOTER_GROUPS = [
  {
    title: 'Browse more designers available for hire',
    links: [
      { label: 'Graphic Designers', url: '/hire/graphic-designers' },
      { label: 'Brand Designers', url: '/hire/brand-designers' },
      { label: 'UI/UX Designers', url: '/hire/ui-ux-designers' },
      { label: 'Illustrators', url: '/hire/illustrators' },
      { label: 'Logo Designers', url: '/hire/logo-designers' },
      { label: 'Interaction Designers', url: '/hire/interaction-designers' },
      { label: 'Art Directors', url: '/hire/art-directors' },
      { label: 'Photographers', url: '/hire/photographers' },
      { label: 'Web Designers', url: '/hire/web-designers' },
      { label: 'Industrial Designers', url: '/hire/industrial-designers' },
      { label: 'Architects', url: '/hire/architects' },
      { label: 'Motion Graphic Designers', url: '/hire/motion-graphic-designers' },
      { label: 'Fashion Artists', url: '/hire/fashion-artists' },
      { label: '3D Artists', url: '/hire/3d-artists' },
      { label: 'Comic Artists', url: '/hire/comic-artists' },
    ],
  },
  {
    title: 'Browse top creative services',
    links: [
      { label: 'Logo Design', url: '/hire/services/logo-design' },
      { label: 'Branding Services', url: '/hire/services/branding-services' },
      { label: 'Social Media Design', url: '/hire/services/social-media-design' },
      { label: 'Website Design', url: '/hire/services/website-design' },
      { label: 'Illustrations', url: '/hire/services/illustrations' },
      { label: 'Packaging Design', url: '/hire/services/packaging-design' },
      { label: 'Landing Page Design', url: '/hire/services/landing-page-design' },
      { label: 'UI/UX Design', url: '/hire/services/ui-ux-design' },
      { label: 'Architecture & Interior Design', url: '/hire/services/architecture-interior-design' },
      { label: 'Portraits', url: '/hire/services/portraits' },
      { label: 'Comics & Character Design', url: '/hire/services/comics-character-design' },
      { label: 'Graphics for Streamers', url: '/hire/services/graphics-for-streamers' },
      { label: 'Mentorship', url: '/hire/services/mentorship' },
      { label: 'Sound Design', url: '/hire/services/sound-design' },
      { label: 'Invitation Design', url: '/hire/services/invitation-design' },
    ],
  },
  {
    title: 'Hiring Freelancers on Behance',
    links: [
      { label: 'How to Hire Freelance Artists on Behance', url: '/blog/hire-freelance-artists-on-behance' },
      { label: 'New Way To Hire Freelancers on Behance: Book a Service', url: '/blog/creative-services' },
      { label: 'Hire Creative Talent for your Next Freelance Job from Behance', url: '/blog/hire-from-behance' },
      { label: 'Help Center: Hiring on Behance', url: 'https://help.behance.net/hc/en-us/categories/203238627-Hiring' },
    ],
  },
]